# Generated by Django 3.2.6 on 2022-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='guid',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='feed',
            name='pub_date',
            field=models.DateField(default='1111-11-11'),
        ),
    ]
