# Generated by Django 3.2.6 on 2022-10-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20221011_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('description', models.CharField(default='No Description', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='source_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.source'),
        ),
    ]
