# Generated by Django 3.2.6 on 2022-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
