# Generated by Django 3.2.6 on 2022-10-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20221012_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
