# Generated by Django 3.2.6 on 2022-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_source_feed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
